version: '3'

services:

    web:
        build:
            context: ./php-apache
        restart: 'always'
        ports:
            - 80:80
        volumes:
            - ./public:/var/www/html
        links:
            - mariadb

    mariadb:
        image: mariadb:10.5
        env_file:
            - .env
        restart: 'always'
        volumes: 
            - mariadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"

volumes:
    mariadb:
