name: Create Diagram

on: [push]

jobs:
  Create-Diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Repo Visualizer
        uses: githubocto/repo-visualizer@0.4.0
